# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 18, 51, 39, 256917, tzinfo=utc), verbose_name='date answered'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 18, 51, 39, 247915, tzinfo=utc), verbose_name='date asked'),
        ),
    ]
