# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170806_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='acount',
            field=models.IntegerField(default=0),
        ),
    ]
