# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_acount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='acount',
            new_name='a_count',
        ),
    ]
